export const host = process.env.REACT_APP_API_URL || 'http://localhost:1000';
console.log(host);
export const registerRoute = `${host}/api/auth/register`;
export const loginRoute = `${host}/api/auth/login`;
export const getUserRoute = `${host}/api/auth/user`;
export const generateAiAvatarRoute = `${host}/api/auth/generate-ai-avatar`;
export const AvtarRoute = `${host}/api/auth/avtar`;
export const logAvatarFallbackRoute = `${host}/api/auth/log-avatar-fallback`;
export const allUsersRoute = `${host}/api/auth/allusers`;
export const contactsWithLastMessageRoute = `${host}/api/auth/contacts-with-last-message`;
console.log(allUsersRoute);
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const getAllMessagesRoute = `${host}/api/messages/getmsg`;
export const markReadRoute = `${host}/api/messages/mark-read`;
export const imageapi = `${host}/api/messages/upload`;
export const createGroupRoute = `${host}/api/groups/create`;
export const getUserGroupsRoute = `${host}/api/groups/user-groups`;
export const addMembersGroupRoute = `${host}/api/groups/add-members`;
export const removeMemberGroupRoute = `${host}/api/groups/remove-member`;
export const makeAdminGroupRoute = `${host}/api/groups/make-admin`;
export const dismissAdminGroupRoute = `${host}/api/groups/dismiss-admin`;
export const updateGroupAvatarRoute = `${host}/api/groups/update-avatar`;
export const leaveGroupRoute = `${host}/api/groups/leave`;
export const deleteGroupRoute = `${host}/api/groups/delete`;
console.log(imageapi);