export const host = process.env.REACT_APP_API_URL || 'http://localhost:1000';
console.log(host);
export const registerRoute = `${host}/api/auth/register`;
export const loginRoute = `${host}/api/auth/login`;
export const AvtarRoute = `${host}/api/auth/avtar`;
export const allUsersRoute = `${host}/api/auth/allusers`;
export const contactsWithLastMessageRoute = `${host}/api/auth/contacts-with-last-message`;
console.log(allUsersRoute);
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const getAllMessagesRoute = `${host}/api/messages/getmsg`;
export const markReadRoute = `${host}/api/messages/mark-read`;
export const imageapi = `${host}/api/messages/upload`;
console.log(imageapi);